/**
 * AI Service — provider-agnostic layer with automatic failover
 *
 * Tries Gemini first; if that fails for ANY reason, retries via Grok.
 * Returns { result, provider } so callers never know which provider served.
 * Logs which provider served each call.
 */
const { callGemini } = require('./geminiProvider');
const { callGrok }   = require('./grokProvider');

// ────────────────────────────────────────────────────────────────
// Core dispatcher
// ────────────────────────────────────────────────────────────────

/**
 * @param {object} opts
 * @param {string} opts.task          — label for logging (e.g. "moderation")
 * @param {string} opts.systemPrompt
 * @param {string} opts.userContent
 * @param {string} [opts.imageBase64]
 * @returns {Promise<{result: any, provider: string}>}
 */
async function callAI({ task, systemPrompt, userContent, imageBase64, responseSchema }) {
  const payload = { systemPrompt, userContent, imageBase64, responseSchema };

  // ── Try Gemini first ──
  try {
    const raw = await callGemini(payload);
    const result = parseJSON(raw);
    console.log(`[AI] ✓ ${task} served by gemini`);
    return { result, provider: 'gemini' };
  } catch (geminiErr) {
    const status = geminiErr.status || 'UNKNOWN_STATUS';
    const msg = geminiErr.message || String(geminiErr);
    console.warn(`[Gemini] model: gemini-3.6-flash / status: ${status} / provider error: ${msg}`);
  }

  // ── Fallback to Grok ──
  try {
    const raw = await callGrok(payload);
    const result = parseJSON(raw);
    console.log(`[AI] ✓ ${task} served by groq`);
    return { result, provider: 'groq' };
  } catch (grokErr) {
    const status = grokErr.status || 'UNKNOWN_STATUS';
    const msg = grokErr.message || String(grokErr);
    console.error(`[Groq] model: fallback / status: ${status} / provider error: ${msg}`);
    throw new Error(`Both AI providers failed for task "${task}". Please try again later.`);
  }
}

/**
 * Extract JSON from a response that may be wrapped in markdown code fences.
 */
function parseJSON(raw) {
  let cleaned = raw.trim();
  // Strip ```json ... ``` wrappers
  const fenced = cleaned.match(/```(?:json)?\s*([\s\S]*?)```/);
  if (fenced) cleaned = fenced[1].trim();
  try {
    return JSON.parse(cleaned);
  } catch {
    // If JSON parse fails, return the raw text as-is (for spotlight/craft free-text)
    return cleaned;
  }
}

/**
 * 0. Check if image is AI-generated (EXCLUSIVELY uses Groq)
 */
async function verifyAIGenerated(imageBase64) {
  const systemPrompt = `You are an AI-detection expert. Analyze this image and determine if it was generated by an AI (like Midjourney, DALL-E, etc.) or if it is a real human-made artwork/photograph. Look for AI artifacts, illogical geometry, weird textures, or blended brushstrokes. Return JSON: {"aiGenerated": boolean, "confidence": number, "reason": string}.`;
  const userContent = 'Please analyze this image.';
  
  try {
    const raw = await callGrok({ systemPrompt, userContent, imageBase64 });
    const result = parseJSON(raw);
    console.log(`[AI] ✓ verification served exclusively by groq`);
    return { result, provider: 'groq' };
  } catch (grokErr) {
    console.error(`[AI] ✗ Groq failed for verification: ${grokErr.message}`);
    throw new Error(`Groq AI verification failed: ${grokErr.message}`);
  }
}

// ────────────────────────────────────────────────────────────────
// High-level task functions
// ────────────────────────────────────────────────────────────────

/**
 * 1. Content moderation — flags ONLY: 18+, violence, hate symbols, spam/ads.
 */
async function moderateContent(imageBase64, note = '') {
  const systemPrompt = `You are a content moderator for an independent art platform. Look at this image and caption. Return JSON: {"safe": boolean, "reason": string}. Flag ONLY: explicit/18+ content, graphic violence, hate symbols, or blatant non-art advertisement. Do not flag based on subject matter, style, skill level, or medium. When in doubt, approve.`;
  const userContent = note ? `Caption: "${note}"` : 'No caption provided.';
  return callAI({ task: 'moderation', systemPrompt, userContent, imageBase64 });
}

/**
 * 2. Tag an artwork image with medium, technique, cultural influence, mood.
 */
async function tagArtwork(imageBase64) {
  const systemPrompt = `Analyze this artwork image. Return JSON: {"medium": string, "technique": string, "cultural_influence": string, "mood": [string]}. Base every tag only on visible evidence in the image — don't guess beyond what's shown.`;
  const userContent = 'Please analyze this artwork and generate tags.';
  return callAI({ task: 'tagging', systemPrompt, userContent, imageBase64 });
}

/**
 * 3. Write an editorial spotlight feature about an artist.
 */
async function writeSpotlight(artistProfile) {
  const systemPrompt = `Write a 150–200 word editorial feature introducing this independent artist to a new audience. Profile: ${JSON.stringify(artistProfile)}. Tone: warm, specific, magazine-quality — avoid generic praise or filler adjectives. Return JSON: {"title": string, "body": string}.`;
  const userContent = `Artist profile: ${JSON.stringify(artistProfile)}`;
  return callAI({ task: 'spotlight', systemPrompt, userContent });
}

/**
 * 4. Generate a step-by-step breakdown of a traditional craft technique.
 */
async function generateCraftBreakdown(description, images = []) {
  const systemPrompt = `A practitioner described this traditional technique: "${description}". Generate a clear 4–8 step breakdown that could teach someone unfamiliar with the tradition. Preserve the practitioner's own terminology where given. Return JSON: {"steps": [string]}.`;
  const userContent = `Technique description: ${description}`;
  const imageBase64 = images.length > 0 ? images[0] : undefined;
  return callAI({ task: 'craft', systemPrompt, userContent, imageBase64 });
}

/**
 * 5. Generate knowledge about a place in India (Explore India Phase 3).
 */
async function generatePlaceKnowledge(placeName, state, country, lat, lon) {
  const systemPrompt = `You are providing educational and travel information about this Indian location.

Provide useful, factual and concise information.
Do not invent coordinates, live weather, current opening hours or unsupported facts.
Return the response using the EXACT following JSON structure:
{
  "placeName": "Name of the place",
  "state": "State",
  "introduction": "Short introduction paragraph",
  "history": "History paragraph",
  "culture": "Culture paragraph",
  "famousFoods": ["Food 1", "Food 2"],
  "placesToVisit": [
    { "name": "Place 1", "description": "Brief desc" }
  ],
  "howToReach": { "air": "Nearest airport info", "rail": "Nearest station info", "road": "Road connectivity info" },
  "bestTimeToVisit": "Best time paragraph",
  "geographicOverview": "Geographic overview paragraph",
  "localTraditions": ["Tradition 1", "Tradition 2"],
  "travelTips": ["Tip 1", "Tip 2"]
}`;

  const userContent = `Place: ${placeName}\nState: ${state}\nCountry: ${country}\nLatitude: ${lat}\nLongitude: ${lon}`;
  
  const responseSchema = {
    type: "OBJECT",
    properties: {
      placeName: { type: "STRING" },
      state: { type: "STRING" },
      introduction: { type: "STRING" },
      history: { type: "STRING" },
      culture: { type: "STRING" },
      famousFoods: { type: "ARRAY", items: { type: "STRING" } },
      placesToVisit: {
        type: "ARRAY",
        items: {
          type: "OBJECT",
          properties: {
            name: { type: "STRING" },
            description: { type: "STRING" }
          },
          required: ["name", "description"]
        }
      },
      howToReach: {
        type: "OBJECT",
        properties: {
          air: { type: "STRING" },
          rail: { type: "STRING" },
          road: { type: "STRING" }
        },
        required: ["air", "rail", "road"]
      },
      bestTimeToVisit: { type: "STRING" },
      geographicOverview: { type: "STRING" },
      localTraditions: { type: "ARRAY", items: { type: "STRING" } },
      travelTips: { type: "ARRAY", items: { type: "STRING" } }
    },
    required: [
      "placeName", "state", "introduction", "history", "culture",
      "famousFoods", "placesToVisit", "howToReach", "bestTimeToVisit",
      "geographicOverview", "localTraditions", "travelTips"
    ]
  };

  return callAI({ task: 'place-knowledge', systemPrompt, userContent, responseSchema });
}

module.exports = {
  callAI,
  verifyAIGenerated,
  moderateContent,
  tagArtwork,
  writeSpotlight,
  generateCraftBreakdown,
  generatePlaceKnowledge,
};
